### ISSUE TITLE
Not to use fmt.Errorf for UnmarshalJSON error

### ISSUE THREAD

**Issue by DhZero** [guregu/null#66]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.15.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
https://play.golang.org/p/7kgBsW80Mzf

### What is the problem?
If we would have not empty **decoder.errorContext.FieldStack** and we received error of **fmt.wrapError** type from UnmarshalJSON then later **addErrorContext** wouldn't be able to set proper value for **err.Field** and **err.Struct** because error type won't match with *UnmarshalTypeError.

https://github.com/golang/go/blob/a7e16abb22f1b249d2691b32a5d20206282898f2/src/encoding/json/decode.go#L181-L183
https://github.com/golang/go/blob/a7e16abb22f1b249d2691b32a5d20206282898f2/src/encoding/json/decode.go#L255-L258

**Comment by guregu** [comment]
Use `errors.As`
https://pkg.go.dev/errors?utm_source=godoc#As

```go
		var jsonError *json.UnmarshalTypeError
		if errors.As(err, &jsonError) {
			// use jsonError
		} else {
			// other kind of error
		}
```

**Comment by DhZero** [comment]
Thanks for fast replay, but how it can help to solve the issue?
Yeah, you can work with error like that after unmarshaling is over but content of error is not going to be fixed.
And I can't make changes in encoding/json package itself.

Maybe I didn't understand your idea, then could you explain it.

**Comment by guregu** [comment]
Oh, my bad! I misunderstood your question, sorry. Thanks for the example code, I see where you're coming from. 
Let me see if there's anything that we can do.

**Comment by guregu** [comment]
OK I understand it now.

We have these options:
- You can use `import "gopkg.in/guregu/null.v3"`, which doesn't wrap the errors.
- We can submit a patch to Go and have them use errors.As instead of a type switch.
- We could stop wrapping errors, but I'd rather not.
- I could add a compile time build tag that changes the behavior, but this would be pretty complex and kind of ugly.

The API for null.v3 and null.v4 is basically the same, so switching to that is the easiest solution.
TBH I think this should count as a bug in the Go standard library, so I think a patch is the cleanest solution.

**Comment by guregu** [comment]
Thanks for making the issue.
Going to link it here to keep track: https://github.com/golang/go/issues/45449
